version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin <your-account-id>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPO_URI=<your-account-id>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/react-app
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - docker build -t $REPO_URI:$IMAGE_TAG .
  post_build:
    commands:
      - docker push $REPO_URI:$IMAGE_TAG
      - echo "Image pushed: $REPO_URI:$IMAGE_TAG"
      - echo "{\"imageUri\":\"$REPO_URI:$IMAGE_TAG\"}" > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
